version: "3.8"

services:
  node-dev-env:
    image: greatgabbar/ci-cd-test
    build: .
    command: npm start
    ports: 
      - 3000:3000
    container_name: node-dev-env
    environment:
      NODE_ENV: development
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower